{% set name = "IMAPClient" %}
{% set version = "2.2.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "de02cedbb5de2f061907fcbfb1a85a1f6ebfb8b5fa523bc003670fb02222e579" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six

test:
  imports:
    - imapclient

about:
  home: http://imapclient.freshfoo.com/
  license: BSD 3-Clause
  license_file: COPYING
  license_family: BSD
  summary: 'Easy-to-use, Pythonic and complete IMAP client library'
  doc_url: http://imapclient.readthedocs.io/
  dev_url: https://github.com/mjs/imapclient

extra:
  recipe-maintainers:
    - pmlandwehr
