{% set name = "IMAPClient" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 78e6d62fbfbbe233e1f0e0e993160fd665eb1fd35973acddc61c15719b22bc02

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - imapclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://imapclient.freshfoo.com/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: Easy-to-use, Pythonic and complete IMAP client library
  doc_url: http://imapclient.readthedocs.io/
  dev_url: https://github.com/mjs/imapclient

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
